name: Docker build

on: "workflow_dispatch"

jobs:
  release:
    name: Docker build
    runs-on: ubuntu-latest
    steps:      
      - if: startsWith(${{ github.event.release.tag_name }}, "v")
        id: version
        run: echo "::set-output name=version::$(echo ${{ github.event.release.tag_name }} | cut -c2-)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: bonukai/mediatracker:${{ steps.version.outputs.version }},bonukai/mediatracker:unstable,bonukai/mediatracker:latest
